# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.

on:
  schedule:
      # every 6 hours
    - cron: "0 */6 * * *"

# This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2

    # Generates the snake  
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: sakshii893
          # these next 2 lines generate the files on a branch called "output". This keeps the main branch from cluttering up.
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

     # show the status of the build. Makes it easier for debugging (if there's any issues).
      - run: git status

      # Push the changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

Reply
 
 
msoftware profile image
Michael jentsch
•
9 Jul 21

Great tutorial! Works for me.
Here's mine - github.com/msoftware


2
 likes
Like

Reply
 
 
gustavohgmartins profile image
Gustavo Martins
•
3 Sept 21

Awsome! How did you change the background-color?


Like

Reply
 
 
mishmanners profile image
Michelle Duke 
•
3 Sept 21

I didn't change the background colour. It's a .png/.svg image, meaning the background is transparent. It looks dark on mine because I have dark mode enabled on GitHub. You can enable it by clicking Settings --> Appearance --> choosing your mode.


1
 like
Like
Thread
 
gustavohgmartins profile image
Gustavo Martins
•
3 Sept 21

Thank you! actually I was using the .gif version, so I switched to the .svg one and voilá


2
 likes
Like
Thread
 
mishmanners profile image
Michelle Duke 
•
3 Sept 21

Awesome! Glad to be of help 😄


1
 like
Like

Reply
 
 
jakon62508112 profile image
Jakob
•
21 Jan 23 • Edited on 21 Jan

Getting this error when I try to run workflow and after it fails:
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.


1
 like
Like

Reply
 
 
shuvajitgeek profile image
Shuvajit
•
2 Feb 23

go to setting -> action -> and check the workflow as read and write
(run build again) hopefully you will not get error


Like

Reply
 
 
l3on06 profile image
Leon Shabani
•
17 Feb 23

Hello everyone, before proceeding, please navigate to 'Settings -> Actions -> General -> Workflow Permissions' in your README.md file and select 'Read and Write' permissions. This is important because if you have other permissions selected, it may result in errors.


2
 likes
Like

Reply
 
 
unknow0074 profile image
Unknown
•
27 May 24

I specially created account to say thank you I almost wasted my 3 hours in wandering around to fix issue and you saved my life.** Thank you**


Like

Reply
 
 
baayah profile image
BAayah
•
11 Jan 24

Thank you so much! I tried to change in settings 'Contribution' to 'include my private contributions' but anyway my Readme profile doesn't show My Contributions. Could you please help me with this?
github.com/BAayah/BAayah


Like

Reply
 
 
ariafatah profile image
Ariafatah
•
18 Sept 23

github.com/ariafatah0711/ariafatah...

Check my github and change this file because I tried the file above only as much as it appears if you want to use the full one I use. And don't forget to give stars😁


1
 like
Like

Reply
 
 
ariafatah profile image
Ariafatah
•
18 Sept 23

If the action fails, you can go to repo settings, click action, then select general, and look at the bottom where it says read and write.


1
 like
Like

Reply
 
 
hoangtien_2k3 profile image
Hoàng Anh Tiến
•
29 Jan 23 • Edited on 29 Jan

It does not work for me. Can someone help me?
github.com/hoangtien2k3qx1

Error:
actions/checkout@v2, platane/snk@master, ad-m/github-push-action@master, and crazy-max/ghaction-github-pages@v2.1.3 are not allowed to be used in hoangtien2k3qx1/hoangtien2k3qx1. Actions in this workflow must be: within a repository owned by hoangtien2k3qx1.


1
 like
Like

Reply
 
 
bpolaswar profile image
Bhumesh Polaswar
•
17 Oct 21

Great worked for me. See github.com/bpolaswar
Thanks.


2
 likes
Like

Reply
View full discussion (50 comments)
Code of Conduct • Report abuse
profile
Bright Data
Promoted

Image of Bright Data and n8n Challenge

SOC-CERT: Automated Threat Intelligence System with n8n & AI
Check out this submission for the AI Agents Challenge powered by n8n and Bright Data.

Read more →


Michelle Duke
Follow
Senior Developer Evangelist | Hackathon Queen | International Speaker
Location
Australia
Education
The University of Melbourne
Joined
29 May 2020
More from Michelle Duke
Razer AIKit: Open-Source, Local-First AI Workflows for Developers
#ai #news #opensource
How to customise the way GitHub Copilot responds
#github #githubcopilot #ai #tutorial
Code, community, and copilot. AI is changing the way we contribute
#devchallenge #hacktoberfest #opensource #ai
profile
Octopus Deploy
Promoted

Using Argo CD? Use Octopus and Argo together to make your GitOps deployment simpler.

Using Argo CD? Use Octopus and Argo together to make your GitOps deployment simpler.
Octopus lets you automate and visualize complex CD scenarios for Argo CD in one product, with a toolbox to manage, verify, and troubleshoot deployments.

Learn More


# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.

on:
  schedule:
      # every 6 hours
    - cron: "0 */6 * * *"

# This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2

    # Generates the snake  
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: mishmanners
          # these next 2 lines generate the files on a branch called "output". This keeps the main branch from cluttering up.
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

     # show the status of the build. Makes it easier for debugging (if there's any issues).
      - run: git status

      # Push the changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
